/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sni;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vladi
 */
public class FrmDepartamentos extends javax.swing.JDialog {
    int idDptoActual;
    QDepartamentos qDepartamentos = new QDepartamentos();
    Tablas tabla = new Tablas();

    /**
     * Creates new form FrmDepartamentos
     */
    public FrmDepartamentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        tblDepartamentos.setModel(llenarDepartamentos());
        tabla.resizeColumnWidth(tblDepartamentos);
    }
    
    public DefaultTableModel llenarDepartamentos(){
        List<Departamentos> departamentos = new ArrayList<Departamentos>();
        DefaultTableModel dtmModelo = new DefaultTableModel();
        
        dtmModelo.addColumn("No.");
        dtmModelo.addColumn("Departamento");
        
        departamentos = qDepartamentos.mostrarDepartamentos();
        
        int i=0;
        for(Departamentos dps:departamentos){
            dtmModelo.addRow(new Object[]{});
            dtmModelo.setValueAt(dps.getId(), i, 0);
            dtmModelo.setValueAt(dps.getDepartamento(), i, 1);
            i++;
        }
        return dtmModelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDepartamentos = new javax.swing.JPanel();
        lblDepartamento = new javax.swing.JLabel();
        txfDepartamento = new javax.swing.JTextField();
        btnAgregarDepartamento = new javax.swing.JButton();
        scpnlDepartamentos = new javax.swing.JScrollPane();
        tblDepartamentos = new javax.swing.JTable();
        btnEditarDepartamentos = new javax.swing.JButton();
        btnEliminarDepartamentos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblNoDepartamento = new javax.swing.JLabel();
        txfNoDepartamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pnlDepartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamentos"));

        lblDepartamento.setText("Departamento:");

        btnAgregarDepartamento.setText("Agregar");
        btnAgregarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDepartamentoActionPerformed(evt);
            }
        });

        tblDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlDepartamentos.setViewportView(tblDepartamentos);

        btnEditarDepartamentos.setText("Editar");
        btnEditarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDepartamentosActionPerformed(evt);
            }
        });

        btnEliminarDepartamentos.setText("Eliminar");
        btnEliminarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepartamentosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblNoDepartamento.setText("N° Departamento:");

        javax.swing.GroupLayout pnlDepartamentosLayout = new javax.swing.GroupLayout(pnlDepartamentos);
        pnlDepartamentos.setLayout(pnlDepartamentosLayout);
        pnlDepartamentosLayout.setHorizontalGroup(
            pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlDepartamentosLayout.createSequentialGroup()
                        .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoDepartamento)
                            .addComponent(lblDepartamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfNoDepartamento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDepartamentosLayout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDepartamentosLayout.createSequentialGroup()
                                .addComponent(btnEditarDepartamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarDepartamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir))
                            .addComponent(btnAgregarDepartamento, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlDepartamentosLayout.setVerticalGroup(
            pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoDepartamento)
                    .addComponent(txfNoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarDepartamento)
                .addGap(18, 18, 18)
                .addComponent(scpnlDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminarDepartamentos)
                    .addComponent(btnEditarDepartamentos)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDepartamentoActionPerformed
        int id;
        String departamento;
        
        try{
            id = Integer.parseInt(txfNoDepartamento.getText());
            departamento = txfDepartamento.getText();
            
            qDepartamentos.agregarDepartamento(id, departamento);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }finally{
            actualizarTabla();
            limpiar();
        }
        
    }//GEN-LAST:event_btnAgregarDepartamentoActionPerformed

    private void btnEditarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDepartamentosActionPerformed
        try{
            if(btnEditarDepartamentos.getText().equals("Editar")){
                btnEditarEditar();
            }else if(btnEditarDepartamentos.getText().equals("Siguiente")){
                btnEditarSiguiente();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        actualizarTabla();
    }//GEN-LAST:event_btnEditarDepartamentosActionPerformed

    private void btnEliminarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepartamentosActionPerformed
        try{
            int row = tblDepartamentos.getSelectedRow();
            int idDpto = Integer.parseInt(tblDepartamentos.getModel().getValueAt(row,0).toString());
            int opcion=JOptionPane.showConfirmDialog(null,"¿Realmente desea eliminar el registro?","Alerta", JOptionPane.YES_NO_OPTION);

            if(opcion==JOptionPane.YES_OPTION){
                if(qDepartamentos.eliminarDepartamento(idDpto)){
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                }else{
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }else{
                JOptionPane.showConfirmDialog(null, "Operacion abortada");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        actualizarTabla();
    }//GEN-LAST:event_btnEliminarDepartamentosActionPerformed

    private void btnEditarEditar(){
        int row = tblDepartamentos.getSelectedRow();
        int idDpto = Integer.parseInt(tblDepartamentos.getModel().getValueAt(row,0).toString());
        String dpto = tblDepartamentos.getModel().getValueAt(row,1).toString();
        
        txfNoDepartamento.setText(String.valueOf(idDpto));
        txfDepartamento.setText(dpto);
        
        tblDepartamentos.setEnabled(false);
        btnSalir.setEnabled(false);
        btnEliminarDepartamentos.setEnabled(false);
        btnAgregarDepartamento.setEnabled(false);
        
        btnEditarDepartamentos.setText("Siguiente");
        
        idDptoActual = idDpto;
        
        txfNoDepartamento.requestFocus();
        
    }
    
    private void btnEditarSiguiente(){
        int opcion=JOptionPane.showConfirmDialog(null,"¿Desea efectuar los cambios?","Alerta", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            if(qDepartamentos.modificarDepartamento(idDptoActual, Integer.parseInt(txfNoDepartamento.getText()), txfDepartamento.getText())){
                JOptionPane.showMessageDialog(null, "Cambios efectuados");
            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Operacion abortada");
        }
        tblDepartamentos.setEnabled(true);
        btnSalir.setEnabled(true);
        btnEliminarDepartamentos.setEnabled(true);
        btnAgregarDepartamento.setEnabled(true);
        
        limpiar();
        
        idDptoActual=0;
        btnEditarDepartamentos.setText("Editar");
    }
    
    public void limpiar(){
        txfNoDepartamento.setText("");
        txfDepartamento.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDepartamentos dialog = new FrmDepartamentos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDepartamento;
    private javax.swing.JButton btnEditarDepartamentos;
    private javax.swing.JButton btnEliminarDepartamentos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblNoDepartamento;
    private javax.swing.JPanel pnlDepartamentos;
    private javax.swing.JScrollPane scpnlDepartamentos;
    private javax.swing.JTable tblDepartamentos;
    private javax.swing.JTextField txfDepartamento;
    private javax.swing.JTextField txfNoDepartamento;
    // End of variables declaration//GEN-END:variables
}
