/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sni;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vladi
 */
public class FrmMunicipios extends javax.swing.JDialog {
    DefaultComboBoxModel modeloDepartamento = new DefaultComboBoxModel();
    List<Departamentos> listaDepartamentos= new ArrayList<Departamentos>();
    QDepartamentos qDepartamentos = new QDepartamentos();
    QMunicipios qMunicipios = new QMunicipios();
    Tablas tabla = new Tablas();
    int idMunActual=0;

    /**
     * Creates new form FrmMunicipios
     */
    public FrmMunicipios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarDepartamentos();
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        tblMunicipios.setModel(llenarMunicipio());
        tabla.resizeColumnWidth(tblMunicipios);
    }
    
    public DefaultTableModel llenarMunicipio(){
        List<Municipios> municipios = new ArrayList<Municipios>();
        DefaultTableModel dtmModelo = new DefaultTableModel();
        
        dtmModelo.addColumn("No.");
        dtmModelo.addColumn("Municipio");
        dtmModelo.addColumn("Departamento");
        
        municipios = qMunicipios.mostrarMunicipiosDepto();
        
        int i=0;
        for(Municipios mps:municipios){
            dtmModelo.addRow(new Object[]{});
            dtmModelo.setValueAt(mps.getIdMunicipio(), i, 0);
            dtmModelo.setValueAt(mps.getMunicipio(), i, 1);
            dtmModelo.setValueAt(mps.getDepartamento(), i, 2);
            i++;
        }
        return dtmModelo;
    }
    
    public void llenarDepartamentos(){
        modeloDepartamento.addElement("--Selecciones Departamento--");
        listaDepartamentos = qDepartamentos.mostrarDepartamentos();
        for(Departamentos d:listaDepartamentos){
            modeloDepartamento.addElement(d.getDepartamento());
        }
        cmbDepartamento.setModel(modeloDepartamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMunicipio = new javax.swing.JPanel();
        lblNoMunicipio = new javax.swing.JLabel();
        txfNoMunicipio = new javax.swing.JTextField();
        lblMunicipio = new javax.swing.JLabel();
        txfMunicipio = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        scpnlMunicipios = new javax.swing.JScrollPane();
        tblMunicipios = new javax.swing.JTable();
        btnEliminarMunicipios = new javax.swing.JButton();
        btnEditarMunicipios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pnlMunicipio.setBorder(javax.swing.BorderFactory.createTitledBorder("Municipios"));

        lblNoMunicipio.setText("N° Municipio:");

        lblMunicipio.setText("Municipio:");

        lblDepartamento.setText("Departamento:");

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlMunicipios.setViewportView(tblMunicipios);

        btnEliminarMunicipios.setText("Eliminar");
        btnEliminarMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMunicipiosActionPerformed(evt);
            }
        });

        btnEditarMunicipios.setText("Editar");
        btnEditarMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMunicipiosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMunicipioLayout = new javax.swing.GroupLayout(pnlMunicipio);
        pnlMunicipio.setLayout(pnlMunicipioLayout);
        pnlMunicipioLayout.setHorizontalGroup(
            pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMunicipioLayout.createSequentialGroup()
                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlMunicipioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMunicipioLayout.createSequentialGroup()
                                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregar)
                                    .addGroup(pnlMunicipioLayout.createSequentialGroup()
                                        .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNoMunicipio)
                                                .addComponent(lblDepartamento))
                                            .addComponent(lblMunicipio, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfNoMunicipio)
                                            .addComponent(txfMunicipio)
                                            .addComponent(cmbDepartamento, 0, 170, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlMunicipioLayout.createSequentialGroup()
                                .addGap(0, 58, Short.MAX_VALUE)
                                .addComponent(btnEliminarMunicipios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarMunicipios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir)))))
                .addContainerGap())
        );
        pnlMunicipioLayout.setVerticalGroup(
            pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoMunicipio)
                    .addComponent(txfNoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartamento)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(scpnlMunicipios, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMunicipios)
                    .addComponent(btnEditarMunicipios)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int id;
        String departamento;
        String municipio;
        
        try{
            id = Integer.parseInt(txfNoMunicipio.getText());
            municipio = txfMunicipio.getText();
            departamento = cmbDepartamento.getSelectedItem().toString();
            
            qMunicipios.agregarMunicipio(id, departamento, municipio);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }finally{
            actualizarTabla();
            limpiar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMunicipiosActionPerformed
        try{
            if(btnEditarMunicipios.getText().equals("Editar")){
                btnEditarEditar();
            }else if(btnEditarMunicipios.getText().equals("Siguiente")){
                btnEditarSiguiente();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        actualizarTabla();
    }//GEN-LAST:event_btnEditarMunicipiosActionPerformed

    private void btnEliminarMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMunicipiosActionPerformed
        try{
            int row = tblMunicipios.getSelectedRow();
            int idMun = Integer.parseInt(tblMunicipios.getModel().getValueAt(row,0).toString());
            int opcion=JOptionPane.showConfirmDialog(null,"¿Realmente desea eliminar el registro?","Alerta", JOptionPane.YES_NO_OPTION);

            if(opcion==JOptionPane.YES_OPTION){
                if(qMunicipios.eliminarMunicipio(idMun)){
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                }else{
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }else{
                JOptionPane.showConfirmDialog(null, "Operacion abortada");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        actualizarTabla();
    }//GEN-LAST:event_btnEliminarMunicipiosActionPerformed

    private void btnEditarEditar(){
        int row = tblMunicipios.getSelectedRow();
        int idMun = Integer.parseInt(tblMunicipios.getModel().getValueAt(row,0).toString());
        String mun = tblMunicipios.getModel().getValueAt(row,1).toString();
        String dep = tblMunicipios.getModel().getValueAt(row,2).toString();
        
        txfNoMunicipio.setText(String.valueOf(idMun));
        txfMunicipio.setText(mun);
        cmbDepartamento.setSelectedItem(dep);
        
        tblMunicipios.setEnabled(false);
        btnSalir.setEnabled(false);
        btnEliminarMunicipios.setEnabled(false);
        btnAgregar.setEnabled(false);
        
        btnEditarMunicipios.setText("Siguiente");
        
        idMunActual = idMun;
        
        txfNoMunicipio.requestFocus();
        
    }
    
    private void btnEditarSiguiente(){
        int opcion=JOptionPane.showConfirmDialog(null,"¿Desea efectuar los cambios?","Alerta", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            if(qMunicipios.modificarMunicipio(idMunActual, Integer.parseInt(txfNoMunicipio.getText()), cmbDepartamento.getSelectedItem().toString(), txfMunicipio.getText())){
                JOptionPane.showMessageDialog(null, "Cambios efectuados");
            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Operacion abortada");
        }
        tblMunicipios.setEnabled(true);
        btnSalir.setEnabled(true);
        btnEliminarMunicipios.setEnabled(true);
        btnAgregar.setEnabled(true);
        
        limpiar();
        
        idMunActual=0;
        btnEditarMunicipios.setText("Editar");
    }
    
    
    public void limpiar(){
        txfMunicipio.setText("");
        txfNoMunicipio.setText("");
        cmbDepartamento.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMunicipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMunicipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMunicipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMunicipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMunicipios dialog = new FrmMunicipios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditarMunicipios;
    private javax.swing.JButton btnEliminarMunicipios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNoMunicipio;
    private javax.swing.JPanel pnlMunicipio;
    private javax.swing.JScrollPane scpnlMunicipios;
    private javax.swing.JTable tblMunicipios;
    private javax.swing.JTextField txfMunicipio;
    private javax.swing.JTextField txfNoMunicipio;
    // End of variables declaration//GEN-END:variables
}
