/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sni;

import java.awt.Color;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author vladi
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        if(!Usuario.isSupersu()){
            initUsuario();
        }else{
            initSuperUsuario();
        }
    }
    
    public void initUsuario(){
        for(int i=1;i<10;i++){
            tbpPrincipal.setEnabledAt(i, false);
        }
        tbpPrincipal.setSelectedIndex(0);
    }
    
    public void initSuperUsuario(){
        setDescripcionGnral();
    }
    
    public void setDescripcionGnral(){
        lblDescripción.setText("Administración general de datos, permite crear o modificar registros base.");
    }
    
    public void relog(){
        Usuario.setLoggeado(false);
        Usuario.setSupersu(false);
        Usuario.setUsuario("");
        FrmLogin lg = new FrmLogin();
        lg.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlBuscar = new javax.swing.JPanel();
        pnlFiltrarDatosBuscar = new javax.swing.JPanel();
        txfFiltrarBuscar = new javax.swing.JTextField();
        cmbFiltrarDatosBuscar = new javax.swing.JComboBox<>();
        btnAplicarFiltroBuscar = new javax.swing.JButton();
        btnLimpiarFiltrosBuscar = new javax.swing.JButton();
        scpnlDatosBuscar = new javax.swing.JScrollPane();
        tblDatosBuscar = new javax.swing.JTable();
        pnlControlBuscar = new javax.swing.JPanel();
        btnGuardarBuscar = new javax.swing.JButton();
        btnImprimirBuscar = new javax.swing.JButton();
        btnSalirBuscar = new javax.swing.JButton();
        lblFiltrosAplicadosBuscar = new javax.swing.JLabel();
        lblFiltrosBuscar = new javax.swing.JLabel();
        pnlEquipoTrabajo = new javax.swing.JPanel();
        pnlBuscarTW = new javax.swing.JPanel();
        lblFiltrarTW = new javax.swing.JLabel();
        txfFiltrarTW = new javax.swing.JTextField();
        btnBuscarTW = new javax.swing.JButton();
        pnlFotoTW = new javax.swing.JPanel();
        pnlDatosTW = new javax.swing.JPanel();
        scpnlTW = new javax.swing.JScrollPane();
        tblTW = new javax.swing.JTable();
        btnAgregarTW = new javax.swing.JButton();
        btnEditarTW = new javax.swing.JButton();
        btnGuardarTW = new javax.swing.JButton();
        btnImprimirTW = new javax.swing.JButton();
        pnlAfiliados = new javax.swing.JPanel();
        pnlBuscarAfiliado = new javax.swing.JPanel();
        lblFiltrarAiliados = new javax.swing.JLabel();
        txfFiltrarAfiliados = new javax.swing.JTextField();
        btnBuscarAfiliados = new javax.swing.JButton();
        pnlFotoAfiliados = new javax.swing.JPanel();
        pnlDatosAfiliado = new javax.swing.JPanel();
        scpnlAfiliados = new javax.swing.JScrollPane();
        tblAfiliados = new javax.swing.JTable();
        btnAgregarAfiliados = new javax.swing.JButton();
        btnEditarAfiliados = new javax.swing.JButton();
        btnGuardarAfiliados = new javax.swing.JButton();
        btnImprimirAfiliados = new javax.swing.JButton();
        pnlCapacitaciones = new javax.swing.JPanel();
        pnlBuscarCapacitaciones = new javax.swing.JPanel();
        lblFiltrarCapacitaciones = new javax.swing.JLabel();
        txfFltrarCapacitaciones = new javax.swing.JTextField();
        btnBuscarCapacitaciones = new javax.swing.JButton();
        pnlFotoCapacitaciones = new javax.swing.JPanel();
        pnlDatosCapacitaciones = new javax.swing.JPanel();
        scpanelCapacitaciones = new javax.swing.JScrollPane();
        tblCapacitaciones = new javax.swing.JTable();
        btnAgregarCapacitaciones = new javax.swing.JButton();
        btnEditarCapacitaciones = new javax.swing.JButton();
        btnGuardarCapacitaciones = new javax.swing.JButton();
        btnImprimirCapacitaciones = new javax.swing.JButton();
        pnlComisiones = new javax.swing.JPanel();
        pnlBuscarComisiones = new javax.swing.JPanel();
        lblFiltrarComisiones = new javax.swing.JLabel();
        txfFiltrarComisiones = new javax.swing.JTextField();
        btnBuscarComisiones = new javax.swing.JButton();
        pnlFotoComisiones = new javax.swing.JPanel();
        pnlDatosComisiones = new javax.swing.JPanel();
        scpnlComisiones = new javax.swing.JScrollPane();
        tblComisiones = new javax.swing.JTable();
        btnAgregarComisiones = new javax.swing.JButton();
        btnEditarComisiones = new javax.swing.JButton();
        btnGuardarComisiones = new javax.swing.JButton();
        btnImprimirComisiones = new javax.swing.JButton();
        pnlCuadroElectoral = new javax.swing.JPanel();
        pnlVotaciones = new javax.swing.JPanel();
        pnlVisitas = new javax.swing.JPanel();
        pnlBuscarVisitas = new javax.swing.JPanel();
        lblFiltrarVisitas = new javax.swing.JLabel();
        txfFiltrarVisitas = new javax.swing.JTextField();
        btnBuscarVisitas = new javax.swing.JButton();
        pnlDatosVisitas = new javax.swing.JPanel();
        pnlFotoVisitas = new javax.swing.JPanel();
        scpnlVisitas = new javax.swing.JScrollPane();
        tblVisitas = new javax.swing.JTable();
        btnAgregarVisitas = new javax.swing.JButton();
        btnEditarVisitas = new javax.swing.JButton();
        btnGuardarVisitas = new javax.swing.JButton();
        btnImprimirVisitas = new javax.swing.JButton();
        pnlFacturacion = new javax.swing.JPanel();
        pnlFiltrarDatosFacturacion = new javax.swing.JPanel();
        txfFiltrarFacturacion = new javax.swing.JTextField();
        cmbFiltrarFacturacion = new javax.swing.JComboBox<>();
        btnAplicarFiltroFacturacion = new javax.swing.JButton();
        btnLimpiarFiltroFacturacion = new javax.swing.JButton();
        scpnlDatosFacturacion = new javax.swing.JScrollPane();
        tblDatosFacturacion = new javax.swing.JTable();
        pnlControlFacturacion = new javax.swing.JPanel();
        btnGuardarFacturacion = new javax.swing.JButton();
        btnImprimirFacturacion = new javax.swing.JButton();
        btnSalirFacturacion = new javax.swing.JButton();
        lblFiltrosAplicadosFacturacion = new javax.swing.JLabel();
        lblFiltrosFacturacion = new javax.swing.JLabel();
        btnNuevaFactura = new javax.swing.JButton();
        pnlControl = new javax.swing.JPanel();
        pnlAdmin = new javax.swing.JPanel();
        btnCargosME = new javax.swing.JButton();
        btnCargoCom = new javax.swing.JButton();
        btnCentroVotacion = new javax.swing.JButton();
        btnComisiones = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnJRV = new javax.swing.JButton();
        btnMunicipios = new javax.swing.JButton();
        btnNivelesAcad = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        pnlDescripcion = new javax.swing.JPanel();
        lblDescripción = new javax.swing.JLabel();
        jmbMenuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenu();
        mnuFacturar = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenu();
        mnuVentana = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 480));

        tbpPrincipal.setPreferredSize(new java.awt.Dimension(720, 480));

        pnlFiltrarDatosBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar datos"));

        cmbFiltrarDatosBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAplicarFiltroBuscar.setText("Aplicar filtro");

        btnLimpiarFiltrosBuscar.setText("Limpiar filtros");

        javax.swing.GroupLayout pnlFiltrarDatosBuscarLayout = new javax.swing.GroupLayout(pnlFiltrarDatosBuscar);
        pnlFiltrarDatosBuscar.setLayout(pnlFiltrarDatosBuscarLayout);
        pnlFiltrarDatosBuscarLayout.setHorizontalGroup(
            pnlFiltrarDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarDatosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfFiltrarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbFiltrarDatosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicarFiltroBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarFiltrosBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltrarDatosBuscarLayout.setVerticalGroup(
            pnlFiltrarDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFiltrarDatosBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFiltrarDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfFiltrarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFiltrarDatosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAplicarFiltroBuscar)
                    .addComponent(btnLimpiarFiltrosBuscar))
                .addContainerGap())
        );

        scpnlDatosBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tblDatosBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlDatosBuscar.setViewportView(tblDatosBuscar);

        pnlControlBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        btnGuardarBuscar.setText("Guardar");

        btnImprimirBuscar.setText("Imprimir");

        btnSalirBuscar.setText("Salir");
        btnSalirBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirBuscarActionPerformed(evt);
            }
        });

        lblFiltrosAplicadosBuscar.setText("Filtros aplicados:");

        lblFiltrosBuscar.setText("Ninguno");

        javax.swing.GroupLayout pnlControlBuscarLayout = new javax.swing.GroupLayout(pnlControlBuscar);
        pnlControlBuscar.setLayout(pnlControlBuscarLayout);
        pnlControlBuscarLayout.setHorizontalGroup(
            pnlControlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrosAplicadosBuscar)
                .addGap(18, 18, 18)
                .addComponent(lblFiltrosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlControlBuscarLayout.setVerticalGroup(
            pnlControlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlBuscarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlControlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarBuscar)
                    .addComponent(btnImprimirBuscar)
                    .addComponent(btnSalirBuscar)
                    .addComponent(lblFiltrosBuscar))
                .addContainerGap())
            .addGroup(pnlControlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrosAplicadosBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlDatosBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(pnlFiltrarDatosBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltrarDatosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpnlDatosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpPrincipal.addTab("Buscar", pnlBuscar);

        pnlBuscarTW.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        lblFiltrarTW.setText("Filtrar:");

        btnBuscarTW.setText("Buscar");

        javax.swing.GroupLayout pnlBuscarTWLayout = new javax.swing.GroupLayout(pnlBuscarTW);
        pnlBuscarTW.setLayout(pnlBuscarTWLayout);
        pnlBuscarTWLayout.setHorizontalGroup(
            pnlBuscarTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarTWLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrarTW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFiltrarTW, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarTW)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBuscarTWLayout.setVerticalGroup(
            pnlBuscarTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarTWLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarTW)
                    .addComponent(txfFiltrarTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFotoTW.setBackground(new java.awt.Color(51, 51, 255));
        pnlFotoTW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoTWLayout = new javax.swing.GroupLayout(pnlFotoTW);
        pnlFotoTW.setLayout(pnlFotoTWLayout);
        pnlFotoTWLayout.setHorizontalGroup(
            pnlFotoTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnlFotoTWLayout.setVerticalGroup(
            pnlFotoTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlDatosTW.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout pnlDatosTWLayout = new javax.swing.GroupLayout(pnlDatosTW);
        pnlDatosTW.setLayout(pnlDatosTWLayout);
        pnlDatosTWLayout.setHorizontalGroup(
            pnlDatosTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosTWLayout.setVerticalGroup(
            pnlDatosTWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tblTW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlTW.setViewportView(tblTW);

        btnAgregarTW.setText("Agregar");

        btnEditarTW.setText("Editar");

        btnGuardarTW.setText("Guardar");

        btnImprimirTW.setText("Imprimir");

        javax.swing.GroupLayout pnlEquipoTrabajoLayout = new javax.swing.GroupLayout(pnlEquipoTrabajo);
        pnlEquipoTrabajo.setLayout(pnlEquipoTrabajoLayout);
        pnlEquipoTrabajoLayout.setHorizontalGroup(
            pnlEquipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipoTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlTW)
                    .addComponent(pnlBuscarTW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEquipoTrabajoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarTW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarTW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarTW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirTW))
                    .addGroup(pnlEquipoTrabajoLayout.createSequentialGroup()
                        .addComponent(pnlFotoTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatosTW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEquipoTrabajoLayout.setVerticalGroup(
            pnlEquipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipoTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEquipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosTW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFotoTW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scpnlTW, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEquipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTW)
                    .addComponent(btnEditarTW)
                    .addComponent(btnAgregarTW)
                    .addComponent(btnImprimirTW))
                .addContainerGap())
        );

        tbpPrincipal.addTab("Equipo de Trabajo", pnlEquipoTrabajo);

        pnlBuscarAfiliado.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        lblFiltrarAiliados.setText("Filtrar:");

        btnBuscarAfiliados.setText("Buscar");

        javax.swing.GroupLayout pnlBuscarAfiliadoLayout = new javax.swing.GroupLayout(pnlBuscarAfiliado);
        pnlBuscarAfiliado.setLayout(pnlBuscarAfiliadoLayout);
        pnlBuscarAfiliadoLayout.setHorizontalGroup(
            pnlBuscarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAfiliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrarAiliados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFiltrarAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAfiliados)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBuscarAfiliadoLayout.setVerticalGroup(
            pnlBuscarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAfiliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarAiliados)
                    .addComponent(txfFiltrarAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAfiliados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFotoAfiliados.setBackground(new java.awt.Color(51, 51, 255));
        pnlFotoAfiliados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoAfiliadosLayout = new javax.swing.GroupLayout(pnlFotoAfiliados);
        pnlFotoAfiliados.setLayout(pnlFotoAfiliadosLayout);
        pnlFotoAfiliadosLayout.setHorizontalGroup(
            pnlFotoAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnlFotoAfiliadosLayout.setVerticalGroup(
            pnlFotoAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlDatosAfiliado.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout pnlDatosAfiliadoLayout = new javax.swing.GroupLayout(pnlDatosAfiliado);
        pnlDatosAfiliado.setLayout(pnlDatosAfiliadoLayout);
        pnlDatosAfiliadoLayout.setHorizontalGroup(
            pnlDatosAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosAfiliadoLayout.setVerticalGroup(
            pnlDatosAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tblAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlAfiliados.setViewportView(tblAfiliados);

        btnAgregarAfiliados.setText("Agregar");

        btnEditarAfiliados.setText("Editar");

        btnGuardarAfiliados.setText("Guardar");

        btnImprimirAfiliados.setText("Imprimir");

        javax.swing.GroupLayout pnlAfiliadosLayout = new javax.swing.GroupLayout(pnlAfiliados);
        pnlAfiliados.setLayout(pnlAfiliadosLayout);
        pnlAfiliadosLayout.setHorizontalGroup(
            pnlAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAfiliadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlAfiliados)
                    .addComponent(pnlBuscarAfiliado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAfiliadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarAfiliados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarAfiliados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarAfiliados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirAfiliados))
                    .addGroup(pnlAfiliadosLayout.createSequentialGroup()
                        .addComponent(pnlFotoAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatosAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAfiliadosLayout.setVerticalGroup(
            pnlAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAfiliadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFotoAfiliados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scpnlAfiliados, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAfiliados)
                    .addComponent(btnEditarAfiliados)
                    .addComponent(btnAgregarAfiliados)
                    .addComponent(btnImprimirAfiliados))
                .addContainerGap())
        );

        tbpPrincipal.addTab("Afiliados", pnlAfiliados);

        pnlBuscarCapacitaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        lblFiltrarCapacitaciones.setText("Filtrar:");

        btnBuscarCapacitaciones.setText("Buscar");

        javax.swing.GroupLayout pnlBuscarCapacitacionesLayout = new javax.swing.GroupLayout(pnlBuscarCapacitaciones);
        pnlBuscarCapacitaciones.setLayout(pnlBuscarCapacitacionesLayout);
        pnlBuscarCapacitacionesLayout.setHorizontalGroup(
            pnlBuscarCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarCapacitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrarCapacitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFltrarCapacitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCapacitaciones)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBuscarCapacitacionesLayout.setVerticalGroup(
            pnlBuscarCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarCapacitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarCapacitaciones)
                    .addComponent(txfFltrarCapacitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCapacitaciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFotoCapacitaciones.setBackground(new java.awt.Color(51, 51, 255));
        pnlFotoCapacitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoCapacitacionesLayout = new javax.swing.GroupLayout(pnlFotoCapacitaciones);
        pnlFotoCapacitaciones.setLayout(pnlFotoCapacitacionesLayout);
        pnlFotoCapacitacionesLayout.setHorizontalGroup(
            pnlFotoCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnlFotoCapacitacionesLayout.setVerticalGroup(
            pnlFotoCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlDatosCapacitaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout pnlDatosCapacitacionesLayout = new javax.swing.GroupLayout(pnlDatosCapacitaciones);
        pnlDatosCapacitaciones.setLayout(pnlDatosCapacitacionesLayout);
        pnlDatosCapacitacionesLayout.setHorizontalGroup(
            pnlDatosCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosCapacitacionesLayout.setVerticalGroup(
            pnlDatosCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tblCapacitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpanelCapacitaciones.setViewportView(tblCapacitaciones);

        btnAgregarCapacitaciones.setText("Agregar");

        btnEditarCapacitaciones.setText("Editar");

        btnGuardarCapacitaciones.setText("Guardar");

        btnImprimirCapacitaciones.setText("Imprimir");

        javax.swing.GroupLayout pnlCapacitacionesLayout = new javax.swing.GroupLayout(pnlCapacitaciones);
        pnlCapacitaciones.setLayout(pnlCapacitacionesLayout);
        pnlCapacitacionesLayout.setHorizontalGroup(
            pnlCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapacitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpanelCapacitaciones)
                    .addComponent(pnlBuscarCapacitaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCapacitacionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCapacitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCapacitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarCapacitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirCapacitaciones))
                    .addGroup(pnlCapacitacionesLayout.createSequentialGroup()
                        .addComponent(pnlFotoCapacitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatosCapacitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCapacitacionesLayout.setVerticalGroup(
            pnlCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapacitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarCapacitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosCapacitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFotoCapacitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scpanelCapacitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapacitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCapacitaciones)
                    .addComponent(btnEditarCapacitaciones)
                    .addComponent(btnAgregarCapacitaciones)
                    .addComponent(btnImprimirCapacitaciones))
                .addContainerGap())
        );

        tbpPrincipal.addTab("Capacitaciones", pnlCapacitaciones);

        pnlBuscarComisiones.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        lblFiltrarComisiones.setText("Filtrar:");

        btnBuscarComisiones.setText("Buscar");

        javax.swing.GroupLayout pnlBuscarComisionesLayout = new javax.swing.GroupLayout(pnlBuscarComisiones);
        pnlBuscarComisiones.setLayout(pnlBuscarComisionesLayout);
        pnlBuscarComisionesLayout.setHorizontalGroup(
            pnlBuscarComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarComisionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrarComisiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFiltrarComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarComisiones)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBuscarComisionesLayout.setVerticalGroup(
            pnlBuscarComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarComisionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarComisiones)
                    .addComponent(txfFiltrarComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComisiones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFotoComisiones.setBackground(new java.awt.Color(51, 51, 255));
        pnlFotoComisiones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoComisionesLayout = new javax.swing.GroupLayout(pnlFotoComisiones);
        pnlFotoComisiones.setLayout(pnlFotoComisionesLayout);
        pnlFotoComisionesLayout.setHorizontalGroup(
            pnlFotoComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnlFotoComisionesLayout.setVerticalGroup(
            pnlFotoComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlDatosComisiones.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout pnlDatosComisionesLayout = new javax.swing.GroupLayout(pnlDatosComisiones);
        pnlDatosComisiones.setLayout(pnlDatosComisionesLayout);
        pnlDatosComisionesLayout.setHorizontalGroup(
            pnlDatosComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosComisionesLayout.setVerticalGroup(
            pnlDatosComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tblComisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlComisiones.setViewportView(tblComisiones);

        btnAgregarComisiones.setText("Agregar");

        btnEditarComisiones.setText("Editar");

        btnGuardarComisiones.setText("Guardar");

        btnImprimirComisiones.setText("Imprimir");

        javax.swing.GroupLayout pnlComisionesLayout = new javax.swing.GroupLayout(pnlComisiones);
        pnlComisiones.setLayout(pnlComisionesLayout);
        pnlComisionesLayout.setHorizontalGroup(
            pnlComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComisionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlComisiones)
                    .addComponent(pnlBuscarComisiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlComisionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarComisiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarComisiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarComisiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirComisiones))
                    .addGroup(pnlComisionesLayout.createSequentialGroup()
                        .addComponent(pnlFotoComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatosComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlComisionesLayout.setVerticalGroup(
            pnlComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComisionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFotoComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scpnlComisiones, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarComisiones)
                    .addComponent(btnEditarComisiones)
                    .addComponent(btnAgregarComisiones)
                    .addComponent(btnImprimirComisiones))
                .addContainerGap())
        );

        tbpPrincipal.addTab("Comisiones", pnlComisiones);

        javax.swing.GroupLayout pnlCuadroElectoralLayout = new javax.swing.GroupLayout(pnlCuadroElectoral);
        pnlCuadroElectoral.setLayout(pnlCuadroElectoralLayout);
        pnlCuadroElectoralLayout.setHorizontalGroup(
            pnlCuadroElectoralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        pnlCuadroElectoralLayout.setVerticalGroup(
            pnlCuadroElectoralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tbpPrincipal.addTab("Cuadro electoral", pnlCuadroElectoral);

        javax.swing.GroupLayout pnlVotacionesLayout = new javax.swing.GroupLayout(pnlVotaciones);
        pnlVotaciones.setLayout(pnlVotacionesLayout);
        pnlVotacionesLayout.setHorizontalGroup(
            pnlVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        pnlVotacionesLayout.setVerticalGroup(
            pnlVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tbpPrincipal.addTab("Votaciones", pnlVotaciones);

        pnlBuscarVisitas.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        lblFiltrarVisitas.setText("Filtrar:");

        btnBuscarVisitas.setText("Buscar");

        javax.swing.GroupLayout pnlBuscarVisitasLayout = new javax.swing.GroupLayout(pnlBuscarVisitas);
        pnlBuscarVisitas.setLayout(pnlBuscarVisitasLayout);
        pnlBuscarVisitasLayout.setHorizontalGroup(
            pnlBuscarVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrarVisitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFiltrarVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarVisitas)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBuscarVisitasLayout.setVerticalGroup(
            pnlBuscarVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarVisitas)
                    .addComponent(txfFiltrarVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVisitas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosVisitas.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout pnlDatosVisitasLayout = new javax.swing.GroupLayout(pnlDatosVisitas);
        pnlDatosVisitas.setLayout(pnlDatosVisitasLayout);
        pnlDatosVisitasLayout.setHorizontalGroup(
            pnlDatosVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosVisitasLayout.setVerticalGroup(
            pnlDatosVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        pnlFotoVisitas.setBackground(new java.awt.Color(51, 51, 255));
        pnlFotoVisitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoVisitasLayout = new javax.swing.GroupLayout(pnlFotoVisitas);
        pnlFotoVisitas.setLayout(pnlFotoVisitasLayout);
        pnlFotoVisitasLayout.setHorizontalGroup(
            pnlFotoVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnlFotoVisitasLayout.setVerticalGroup(
            pnlFotoVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlVisitas.setViewportView(tblVisitas);

        btnAgregarVisitas.setText("Agregar");

        btnEditarVisitas.setText("Editar");

        btnGuardarVisitas.setText("Guardar");

        btnImprimirVisitas.setText("Imprimir");

        javax.swing.GroupLayout pnlVisitasLayout = new javax.swing.GroupLayout(pnlVisitas);
        pnlVisitas.setLayout(pnlVisitasLayout);
        pnlVisitasLayout.setHorizontalGroup(
            pnlVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlVisitas)
                    .addComponent(pnlBuscarVisitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlVisitasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarVisitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarVisitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarVisitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirVisitas))
                    .addGroup(pnlVisitasLayout.createSequentialGroup()
                        .addComponent(pnlFotoVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatosVisitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVisitasLayout.setVerticalGroup(
            pnlVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosVisitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFotoVisitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scpnlVisitas, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVisitas)
                    .addComponent(btnEditarVisitas)
                    .addComponent(btnAgregarVisitas)
                    .addComponent(btnImprimirVisitas))
                .addContainerGap())
        );

        tbpPrincipal.addTab("Visitas", pnlVisitas);

        pnlFiltrarDatosFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar datos"));

        cmbFiltrarFacturacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAplicarFiltroFacturacion.setText("Aplicar filtro");

        btnLimpiarFiltroFacturacion.setText("Limpiar filtros");

        javax.swing.GroupLayout pnlFiltrarDatosFacturacionLayout = new javax.swing.GroupLayout(pnlFiltrarDatosFacturacion);
        pnlFiltrarDatosFacturacion.setLayout(pnlFiltrarDatosFacturacionLayout);
        pnlFiltrarDatosFacturacionLayout.setHorizontalGroup(
            pnlFiltrarDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarDatosFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfFiltrarFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbFiltrarFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicarFiltroFacturacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarFiltroFacturacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltrarDatosFacturacionLayout.setVerticalGroup(
            pnlFiltrarDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFiltrarDatosFacturacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFiltrarDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfFiltrarFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFiltrarFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAplicarFiltroFacturacion)
                    .addComponent(btnLimpiarFiltroFacturacion))
                .addContainerGap())
        );

        scpnlDatosFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tblDatosFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnlDatosFacturacion.setViewportView(tblDatosFacturacion);

        pnlControlFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        btnGuardarFacturacion.setText("Guardar");

        btnImprimirFacturacion.setText("Imprimir");

        btnSalirFacturacion.setText("Salir");
        btnSalirFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFacturacionActionPerformed(evt);
            }
        });

        lblFiltrosAplicadosFacturacion.setText("Filtros aplicados:");

        lblFiltrosFacturacion.setText("Ninguno");

        btnNuevaFactura.setText("Nueva Factura");

        javax.swing.GroupLayout pnlControlFacturacionLayout = new javax.swing.GroupLayout(pnlControlFacturacion);
        pnlControlFacturacion.setLayout(pnlControlFacturacionLayout);
        pnlControlFacturacionLayout.setHorizontalGroup(
            pnlControlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrosAplicadosFacturacion)
                .addGap(18, 18, 18)
                .addComponent(lblFiltrosFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevaFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirFacturacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarFacturacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlControlFacturacionLayout.setVerticalGroup(
            pnlControlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlFacturacionLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlControlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarFacturacion)
                    .addComponent(btnImprimirFacturacion)
                    .addComponent(btnSalirFacturacion)
                    .addComponent(lblFiltrosFacturacion)
                    .addComponent(btnNuevaFactura))
                .addContainerGap())
            .addGroup(pnlControlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrosAplicadosFacturacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFacturacionLayout = new javax.swing.GroupLayout(pnlFacturacion);
        pnlFacturacion.setLayout(pnlFacturacionLayout);
        pnlFacturacionLayout.setHorizontalGroup(
            pnlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpnlDatosFacturacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(pnlFiltrarDatosFacturacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControlFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFacturacionLayout.setVerticalGroup(
            pnlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltrarDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpnlDatosFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControlFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpPrincipal.addTab("Facturación", pnlFacturacion);

        pnlAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar"));
        pnlAdmin.setPreferredSize(new java.awt.Dimension(695, 210));

        btnCargosME.setText("Cargos de Miembros Electorales");

        btnCargoCom.setText("Cargos de comisionados");

        btnCentroVotacion.setText("Centros de votación");
        btnCentroVotacion.setPreferredSize(new java.awt.Dimension(200, 45));

        btnComisiones.setText("Comisiones");
        btnComisiones.setPreferredSize(new java.awt.Dimension(200, 45));

        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.setPreferredSize(new java.awt.Dimension(200, 45));
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnJRV.setText("Juntas receptoras de votos");
        btnJRV.setPreferredSize(new java.awt.Dimension(200, 45));

        btnMunicipios.setText("Municipios");
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });

        btnNivelesAcad.setText("Niveles académicos");

        btnPartidos.setText("Partidos políticos");
        btnPartidos.setPreferredSize(new java.awt.Dimension(200, 45));

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCargoCom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargosME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCentroVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJRV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMunicipios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNivelesAcad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargosME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComisiones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMunicipios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargoCom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNivelesAcad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnCentroVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJRV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        pnlDescripcion.setPreferredSize(new java.awt.Dimension(695, 210));

        lblDescripción.setText("Texto descriptivo");

        javax.swing.GroupLayout pnlDescripcionLayout = new javax.swing.GroupLayout(pnlDescripcion);
        pnlDescripcion.setLayout(pnlDescripcionLayout);
        pnlDescripcionLayout.setHorizontalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripción)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDescripcionLayout.setVerticalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripción)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(pnlDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpPrincipal.addTab("Panel de Control", pnlControl);

        mnuArchivo.setText("Archivo");

        mnuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoSalir);

        jmbMenuBar.add(mnuArchivo);

        mnuEditar.setText("Editar");
        jmbMenuBar.add(mnuEditar);

        mnuFacturar.setText("Facturar");
        jmbMenuBar.add(mnuFacturar);

        mnuUsuario.setText("Usuario");
        jmbMenuBar.add(mnuUsuario);

        mnuVentana.setText("Ventana");
        jmbMenuBar.add(mnuVentana);

        mnuAyuda.setText("Ayuda");
        jmbMenuBar.add(mnuAyuda);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirBuscarActionPerformed
        salir();
    }//GEN-LAST:event_btnSalirBuscarActionPerformed

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed
        salir();
    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    private void btnSalirFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFacturacionActionPerformed
        salir();
    }//GEN-LAST:event_btnSalirFacturacionActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        FrmDepartamentos dp=new FrmDepartamentos(this,true);
        dp.main();
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        FrmMunicipios mun=new FrmMunicipios(this,true);
        mun.main();
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAfiliados;
    private javax.swing.JButton btnAgregarCapacitaciones;
    private javax.swing.JButton btnAgregarComisiones;
    private javax.swing.JButton btnAgregarTW;
    private javax.swing.JButton btnAgregarVisitas;
    private javax.swing.JButton btnAplicarFiltroBuscar;
    private javax.swing.JButton btnAplicarFiltroFacturacion;
    private javax.swing.JButton btnBuscarAfiliados;
    private javax.swing.JButton btnBuscarCapacitaciones;
    private javax.swing.JButton btnBuscarComisiones;
    private javax.swing.JButton btnBuscarTW;
    private javax.swing.JButton btnBuscarVisitas;
    private javax.swing.JButton btnCargoCom;
    private javax.swing.JButton btnCargosME;
    private javax.swing.JButton btnCentroVotacion;
    private javax.swing.JButton btnComisiones;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnEditarAfiliados;
    private javax.swing.JButton btnEditarCapacitaciones;
    private javax.swing.JButton btnEditarComisiones;
    private javax.swing.JButton btnEditarTW;
    private javax.swing.JButton btnEditarVisitas;
    private javax.swing.JButton btnGuardarAfiliados;
    private javax.swing.JButton btnGuardarBuscar;
    private javax.swing.JButton btnGuardarCapacitaciones;
    private javax.swing.JButton btnGuardarComisiones;
    private javax.swing.JButton btnGuardarFacturacion;
    private javax.swing.JButton btnGuardarTW;
    private javax.swing.JButton btnGuardarVisitas;
    private javax.swing.JButton btnImprimirAfiliados;
    private javax.swing.JButton btnImprimirBuscar;
    private javax.swing.JButton btnImprimirCapacitaciones;
    private javax.swing.JButton btnImprimirComisiones;
    private javax.swing.JButton btnImprimirFacturacion;
    private javax.swing.JButton btnImprimirTW;
    private javax.swing.JButton btnImprimirVisitas;
    private javax.swing.JButton btnJRV;
    private javax.swing.JButton btnLimpiarFiltroFacturacion;
    private javax.swing.JButton btnLimpiarFiltrosBuscar;
    private javax.swing.JButton btnMunicipios;
    private javax.swing.JButton btnNivelesAcad;
    private javax.swing.JButton btnNuevaFactura;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnSalirBuscar;
    private javax.swing.JButton btnSalirFacturacion;
    private javax.swing.JComboBox<String> cmbFiltrarDatosBuscar;
    private javax.swing.JComboBox<String> cmbFiltrarFacturacion;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JLabel lblDescripción;
    private javax.swing.JLabel lblFiltrarAiliados;
    private javax.swing.JLabel lblFiltrarCapacitaciones;
    private javax.swing.JLabel lblFiltrarComisiones;
    private javax.swing.JLabel lblFiltrarTW;
    private javax.swing.JLabel lblFiltrarVisitas;
    private javax.swing.JLabel lblFiltrosAplicadosBuscar;
    private javax.swing.JLabel lblFiltrosAplicadosFacturacion;
    private javax.swing.JLabel lblFiltrosBuscar;
    private javax.swing.JLabel lblFiltrosFacturacion;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoSalir;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuEditar;
    private javax.swing.JMenu mnuFacturar;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JMenu mnuVentana;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlAfiliados;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlBuscarAfiliado;
    private javax.swing.JPanel pnlBuscarCapacitaciones;
    private javax.swing.JPanel pnlBuscarComisiones;
    private javax.swing.JPanel pnlBuscarTW;
    private javax.swing.JPanel pnlBuscarVisitas;
    private javax.swing.JPanel pnlCapacitaciones;
    private javax.swing.JPanel pnlComisiones;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlControlBuscar;
    private javax.swing.JPanel pnlControlFacturacion;
    private javax.swing.JPanel pnlCuadroElectoral;
    private javax.swing.JPanel pnlDatosAfiliado;
    private javax.swing.JPanel pnlDatosCapacitaciones;
    private javax.swing.JPanel pnlDatosComisiones;
    private javax.swing.JPanel pnlDatosTW;
    private javax.swing.JPanel pnlDatosVisitas;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlEquipoTrabajo;
    private javax.swing.JPanel pnlFacturacion;
    private javax.swing.JPanel pnlFiltrarDatosBuscar;
    private javax.swing.JPanel pnlFiltrarDatosFacturacion;
    private javax.swing.JPanel pnlFotoAfiliados;
    private javax.swing.JPanel pnlFotoCapacitaciones;
    private javax.swing.JPanel pnlFotoComisiones;
    private javax.swing.JPanel pnlFotoTW;
    private javax.swing.JPanel pnlFotoVisitas;
    private javax.swing.JPanel pnlVisitas;
    private javax.swing.JPanel pnlVotaciones;
    private javax.swing.JScrollPane scpanelCapacitaciones;
    private javax.swing.JScrollPane scpnlAfiliados;
    private javax.swing.JScrollPane scpnlComisiones;
    private javax.swing.JScrollPane scpnlDatosBuscar;
    private javax.swing.JScrollPane scpnlDatosFacturacion;
    private javax.swing.JScrollPane scpnlTW;
    private javax.swing.JScrollPane scpnlVisitas;
    private javax.swing.JTable tblAfiliados;
    private javax.swing.JTable tblCapacitaciones;
    private javax.swing.JTable tblComisiones;
    private javax.swing.JTable tblDatosBuscar;
    private javax.swing.JTable tblDatosFacturacion;
    private javax.swing.JTable tblTW;
    private javax.swing.JTable tblVisitas;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txfFiltrarAfiliados;
    private javax.swing.JTextField txfFiltrarBuscar;
    private javax.swing.JTextField txfFiltrarComisiones;
    private javax.swing.JTextField txfFiltrarFacturacion;
    private javax.swing.JTextField txfFiltrarTW;
    private javax.swing.JTextField txfFiltrarVisitas;
    private javax.swing.JTextField txfFltrarCapacitaciones;
    // End of variables declaration//GEN-END:variables

    public void salir(){
        System.exit(0);
    }

}